### ISSUE TITLE
Gain access to the DAP

### ISSUE THREAD

**Issue by rhfallon** [Shrenil19/BrainyPhonics#13]

**Comment by rhfallon** [comment]
Please reach out to Dr. Evans as needed, and gain access to the DAP.

Upon completion, please write a brief description of how it can be accessed and utilized to push and pull information from the server for later use. Ie, how a programmer would use it to get information, post information, and ideally, add an example of code using the DAP.

**Comment by Shrenil19** [comment]
Access to DAP is as follows:

Source Code: https://github.com/BrainyEducation/Brainy-Kids (read the instructions in the readmeO

WebPortal: http://teacherportal.hearatale.com/ (create your own account and login to it)
