### ISSUE TITLE
Validate Student Login Information with the DAP - BackEnd

### ISSUE THREAD

**Issue by rhfallon** [Shrenil19/BrainyPhonics#16]
This ticket relies on the completion of the student login page. 

When a student clicks "submit," please validate their saved login information against the DAP to ensure a student exists for this information. 

If one does not, please prompt them to try again, or get in touch with an administrator. 

If it does, successful login should start the lessons menu activity.

**Comment by Shrenil19** [comment]
running instance of mongoDB on cloud server: 

IP: 45.76.254.167

Root password: @6SyCb+T(HF8h?@q

@ceelo777 @chromeoverload @lauracvg @lauracvg

**Comment by Shrenil19** [comment]
access MongoDB running on vulture:

1. SSH into the server via instructions in previous comment. 
2. Type: npm run dev in the 'snap' directory
3. verify mongoDB service is running by typing into browser: 45.76.254.167

Link local app to point to the instance by setting MONGODB_URI to the server location (45.76.254.167)

### PLEASE MAKE SURE TO TERMINATE THE MONGODB SERVICE ONCE UR DONE SO IT DOESNT KEEP RUNNING AND RACK UP ALOTTA CHARGES ON THE SERVER PLZ :)
