### ISSUE TITLE
DUE 4/4 - Sprint 4 Demo & Video

### ISSUE THREAD

**Issue by rhfallon** [Shrenil19/BrainyPhonics#34]
See canvas for details. 

Feedback from Stallworth from meeting @Shrenil19:

- Put project name on title slide
- Say what we were supposed to do in this sprint (bullet points)
- Say what we’re going to tell them (bullets)
- As we show each implementation, put the words describing that feature on the screen
- Emulator is too small
-  He expects to see a full soup to nuts lesson for this demo

**Comment by Shrenil19** [comment]
changed date to 4/4
